[package]
name = "nitric"
version = "0.1.0"
authors = ["Thomas Schaller <torkleyy@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam-deque = "0.6.2"
futures-preview = "0.3.0-alpha.9"
parking_lot = { path = "../parking_lot" }
parking_lot_core = { path = "../parking_lot/core" }
rayon = "1"
